openapi: 3.0.0
info:
  title: AI Research POC API
  description: AI時代の新しいリサーチ体験を探索するPOC API
  version: 0.1.0

servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /research:
    post:
      summary: リサーチを実行
      operationId: executeResearch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateResearchRequest"
      responses:
        "202":
          description: リサーチ受付
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResearchSnapshot"
        "400":
          description: 無効なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /research/{id}:
    get:
      summary: リサーチスナップショットを取得
      operationId: getResearchSnapshot
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: リサーチスナップショット
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResearchSnapshot"
        "404":
          description: 見つかりません
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /research/{id}/events:
    get:
      summary: リサーチイベントのSSEストリーム
      operationId: streamResearchEvents
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: lastEventId
          required: false
          schema:
            type: string
      responses:
        "200":
          description: SSEイベントストリーム
          content:
            text/event-stream:
              schema:
                type: string

  /research/{id}/re-execute:
    post:
      summary: 追いリサーチを実行
      operationId: reExecuteResearch
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "202":
          description: 追いリサーチ受付
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResearchSnapshot"
        "404":
          description: 見つかりません
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /query-optimization:
    post:
      summary: クエリ最適化を実行
      operationId: optimizeQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryOptimizationRequest"
      responses:
        "200":
          description: 最適化結果
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OptimizationResponse"
        "400":
          description: 無効なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    QueryOptimizationRequest:
      type: object
      required:
        - originalQuery
      properties:
        originalQuery:
          type: string
          minLength: 1
          description: 元の曖昧クエリ
        selectedText:
          type: string
          description: 選択テキスト
        voiceCommand:
          $ref: "#/components/schemas/VoicePattern"
        voiceTranscript:
          type: string
          description: 音声認識から得られた元のテキスト
        sessionId:
          type: string
          description: クエリ最適化セッションID
        researchHistory:
          type: array
          items:
            $ref: "#/components/schemas/Research"
          description: 過去のリサーチ履歴
        userContext:
          type: object
          nullable: true
          properties:
            interests:
              type: array
              items:
                type: string
            expertise:
              type: array
              items:
                type: string
            previousOptimizations:
              type: array
              items:
                $ref: "#/components/schemas/OptimizationResult"

    OptimizationResult:
      type: object
      required:
        - candidates
      properties:
        candidates:
          type: array
          minItems: 1
          description: 最適化されたクエリ候補の一覧
          items:
            $ref: "#/components/schemas/OptimizationCandidate"
        evaluationSummary:
          type: string
          description: 候補全体に関するまとめとアドバイス
        recommendedCandidateId:
          type: string
          description: LLMが推奨する候補のID

    OptimizationResponse:
      type: object
      required:
        - sessionId
        - result
      properties:
        sessionId:
          type: string
          description: クエリ最適化セッションID
        result:
          $ref: "#/components/schemas/OptimizationResult"

    OptimizationCandidate:
      type: object
      required:
        - id
        - query
        - coverageScore
        - coverageExplanation
      properties:
        id:
          type: string
          description: 候補を一意に識別するID
        query:
          type: string
          description: 提案クエリ
        coverageScore:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: ユーザー要件を満たしている度合い（0-1）
        coverageExplanation:
          type: string
          description: スコアの理由や含まれる要件の説明
        addedAspects:
          type: array
          items:
            type: string
          description: 特に補強した観点
        improvementReason:
          type: string
          description: クエリがどのように改善されたか
        suggestedFollowups:
          type: array
          items:
            type: string
          description: 候補クエリに基づく追加調査案
    Research:
      type: object
      required:
        - id
        - query
        - status
        - createdAt
      properties:
        id:
          type: string
          description: リサーチID
        query:
          type: string
          description: 初期クエリ
        status:
          type: string
          enum: [pending, completed, failed]
          description: リサーチ状態
        results:
          type: array
          items:
            $ref: "#/components/schemas/ResearchResult"
          description: リサーチ結果
        searchResults:
          type: array
          items:
            $ref: "#/components/schemas/SearchResult"
          description: Perplexity検索結果
        citations:
          type: array
          items:
            type: string
          description: 引用URL一覧
        createdAt:
          type: string
          format: date-time
          description: 作成日時
        updatedAt:
          type: string
          format: date-time
          description: 更新日時

    ResearchResult:
      type: object
      required:
        - id
        - content
        - source
      properties:
        id:
          type: string
          description: 結果ID
        content:
          type: string
          description: HTML化されたリサーチ結果内容
        source:
          type: string
          description: 情報源
        relevanceScore:
          type: number
          format: float
          description: 関連度スコア
        voicePattern:
          $ref: "#/components/schemas/VoicePattern"
        processedCitations:
          type: array
          items:
            $ref: "#/components/schemas/ProcessedCitation"
          description: 構造化された引用情報
    ResearchSnapshot:
      type: object
      required:
        - id
        - query
        - status
        - revision
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          description: リサーチID
        query:
          type: string
          description: 初期クエリ
        selectedText:
          type: string
          nullable: true
          description: 選択されたテキスト
        voiceCommand:
          type: string
          nullable: true
          description: 音声コマンド（構造化済み）
        status:
          type: string
          enum: [pending, completed, failed]
          description: リサーチ状態
        revision:
          type: integer
          minimum: 1
          description: スナップショットのリビジョン
        results:
          type: array
          items:
            $ref: "#/components/schemas/ResearchResultSnapshot"
        searchResults:
          type: array
          items:
            $ref: "#/components/schemas/ResearchSearchResultSnapshot"
        citations:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        lastError:
          type: object
          nullable: true
          properties:
            message:
              type: string
            code:
              type: string
    ResearchResultSnapshot:
      type: object
      required:
        - id
        - content
        - source
        - relevanceScore
      properties:
        id:
          type: string
        content:
          type: string
        source:
          type: string
        relevanceScore:
          type: number
        processedCitations:
          type: array
          items:
            $ref: "#/components/schemas/ProcessedCitationSnapshot"
          nullable: true
    ProcessedCitationSnapshot:
      type: object
      required:
        - id
        - number
        - url
      properties:
        id:
          type: string
        number:
          type: integer
        url:
          type: string
          format: uri
        title:
          type: string
          nullable: true
        domain:
          type: string
          nullable: true
    ResearchSearchResultSnapshot:
      type: object
      required:
        - id
        - title
        - url
      properties:
        id:
          type: string
        title:
          type: string
        url:
          type: string
          format: uri
        snippet:
          type: string
          nullable: true
        relevanceScore:
          type: number
          nullable: true
        lastUpdated:
          type: string
          format: date-time
          nullable: true

    VoicePattern:
      type: string
      enum:
        - deepdive
        - perspective
        - concrete
        - data
        - compare
        - trend
        - practical
        - summary
      description: 音声解釈パターン

    CreateResearchRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          minLength: 1
          description: リサーチクエリ
        selectedText:
          type: string
          description: 選択されたテキスト
        voiceCommand:
          type: string
          description: 音声コマンド
        voiceTranscript:
          type: string
          description: 音声認識から得られた元のテキスト

    SearchResult:
      type: object
      required:
        - title
        - url
        - snippet
      properties:
        title:
          type: string
          description: ページタイトル
        url:
          type: string
          description: ページURL
        snippet:
          type: string
          description: ページ概要
        date:
          type: string
          nullable: true
          description: 記事作成日（オプショナル）
        last_updated:
          type: string
          nullable: true
          description: 最終更新日（オプショナル）

    ProcessedCitation:
      type: object
      required:
        - id
        - number
        - url
      properties:
        id:
          type: string
          description: 引用ID（ref1, ref2など）
        number:
          type: number
          description: 引用番号（1, 2など）
        url:
          type: string
          description: 引用URL
        title:
          type: string
          nullable: true
          description: 引用タイトル
        domain:
          type: string
          nullable: true
          description: 引用ドメイン

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: エラーメッセージ
        code:
          type: string
          description: エラーコード
