openapi: 3.0.0
info:
  title: AI Research POC API
  description: AI時代の新しいリサーチ体験を探索するPOC API
  version: 0.1.0

servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /research:
    post:
      summary: リサーチを実行
      operationId: executeResearch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateResearchRequest"
      responses:
        "200":
          description: リサーチ完了
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Research"
        "400":
          description: 無効なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Research:
      type: object
      required:
        - id
        - query
        - status
        - createdAt
      properties:
        id:
          type: string
          description: リサーチID
        query:
          type: string
          description: 初期クエリ
        status:
          type: string
          enum: [pending, completed, failed]
          description: リサーチ状態
        results:
          type: array
          items:
            $ref: "#/components/schemas/ResearchResult"
          description: リサーチ結果
        createdAt:
          type: string
          format: date-time
          description: 作成日時
        updatedAt:
          type: string
          format: date-time
          description: 更新日時

    ResearchResult:
      type: object
      required:
        - id
        - content
        - source
      properties:
        id:
          type: string
          description: 結果ID
        content:
          type: string
          description: リサーチ結果内容
        source:
          type: string
          description: 情報源
        relevanceScore:
          type: number
          format: float
          description: 関連度スコア
        voicePattern:
          $ref: "#/components/schemas/VoicePattern"

    VoicePattern:
      type: string
      enum:
        - deepdive
        - perspective
        - concrete
        - data
        - compare
        - trend
        - practical
        - summary
      description: 音声解釈パターン

    CreateResearchRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          minLength: 1
          description: リサーチクエリ
        selectedText:
          type: string
          description: 選択されたテキスト
        voiceCommand:
          type: string
          description: 音声コマンド

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: エラーメッセージ
        code:
          type: string
          description: エラーコード
